services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - main

networks:
  main:
